### ISSUE TITLE
Как подать заявку

### ISSUE THREAD

**Issue by nadezhdakuzmina** [avito-tech/sx-frontend-trainee-assignment#3]
Добрый день! Я хотела бы попасть на стажировку, но форма почему-то уже закрыта, хотя тестовое задание можно выполнить до 10 сентября. Возможно ли как-то решить это?
telegram Kuzmina_na

**Comment by proehavshiy** [comment]
плюсую, мне тоже интересно. Но, насколько я узнавал уже, стажировка закрыта, а инфа на сайтах просто устарела. Вроде бы, набор (если будет), то с конца августа/начала сентября
